name: D'Oger
favicon: null
layout_spectrum: 0.6015190547332168
typography_spectrum: 0.5067755423951894
title: D'Arcy < D'Oger > Roger
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.31698307883925736
  lightness: 0.12340022134594619
  saturation: 0.9500292304437608
  rhythmicContrast: 0.029150678776204586
purpose: []
